name: LibCal Booker

on:
  # enables testing
  workflow_dispatch:

  # Scheduler
  schedule:
    # This runs at 7:00 AM UTC, 2:00 AM Chicago Time (CDT)
    - cron: '0 7 * * *'

jobs:
  book-room:
    # Runs the job on a server hosted by GitHub
    runs-on: ubuntu-latest

    steps:
      # download code from repo
      - name: Check out repository
        uses: actions/checkout@v4

      # set up python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt
          
      # install browsers
      - name: Install Playwright Browsers
        run: playwright install --with-deps

      # run script
      - name: Run booking script
        run: python book.py
